docs: translate `docs/roadmap.md` into Chinese
docschina/babeljs-cn pull request #126
Opened 2022-01-28 09:16 UTC by htmlin

2022-02-06 16:13 UTC, KimYangOfCat requested changes
感谢你的翻译，非常棒！

2022-02-06 16:13 UTC, KimYangOfCat commented on docs/roadmap.md
> +这远非我们将为 Babel 带来的所有新功能或重要更改的完整列表，但是，如果你对项目发展的大方向感兴趣，那么这是一个很好的总结。实际上，我们可能不能完成所有列出的要点，或者可能会将其中一些推迟到明年。其中一些有明确的起点和终点，而另一些则需要更多的研究或 [RFCs](https://github.com/babel/rfcs)。
```suggestion
这并不是我们将为 Babel 带来的所有新功能或重要更改的完整列表，但是，如果你对项目发展的大方向感兴趣，那么这是一个很好的总结。实际上，我们也许并不能完成列出的所有要点，甚至可能会将某些实现推迟到明年。某些要点已有明确的起止时间，而另一些则需要更多的研究或 [RFCs](https://github.com/babel/rfcs)。
```

2022-02-06 16:13 UTC, KimYangOfCat commented on docs/roadmap.md
> +如果贵公司有兴趣并希望直接赞助任何项目，请 [联系我们](mail:team@babeljs.io)！
```suggestion
如果贵公司有兴趣并希望直接赞助，请 [联系我们](mail:team@babeljs.io)！
```

2022-02-06 16:13 UTC, KimYangOfCat commented on docs/roadmap.md
> +关于 Babel 8 的发布我们已经讨论了一年多了（我们最初是在一年前安排的）！不过，我们现在比以往任何时候都离它的发布更近！
```suggestion
关于 Babel 8 的发布我们已经讨论了一年多了（我们早在一年前就有了安排）！不过相比之前，我们现在离它的发布越来越近了！
```

2022-02-06 16:13 UTC, KimYangOfCat commented on docs/roadmap.md
> +- 我们正在尝试将我们的 TypeScript AST 与 [`typescript-eslint`](https://github.com/typescript-eslint/typescript-eslint/) 项目对齐。我们的 AST _几乎_ 完全相同，但我们还需要引入一些小的突破性变化才能完全一致。
```suggestion
- 我们正在尝试将我们的 TypeScript AST 项目与 [`typescript-eslint`](https://github.com/typescript-eslint/typescript-eslint/) 项目对齐。它们的 AST _几乎_ 完全相同，但我们还需要做出一些小的突破性更改，才能完全一致。
```

2022-02-06 16:13 UTC, KimYangOfCat commented on docs/roadmap.md
> +Babel 目前可以解析所有第 3 阶段提案，除了顶级 await、导入断言和 JSON 模块（它们最好由使用依赖关系图的构建工具来处理）之外，我们都可以转译它们。
```suggestion
除了顶级 await、导入断言和 JSON 模块（它们最好由使用依赖关系图的构建工具来处理）之外，Babel 目前可以解析并转译所有第 3 阶段提案。
```

2022-02-06 16:13 UTC, KimYangOfCat commented on docs/roadmap.md
> +尽管我们不支持许多第 1 阶段提案，但最近对管道运算符和 to do 表达式进行了更新。因为我们已经支持这些提案，并且社区对它们非常期待，所以我们将更新我们的实现。
```suggestion
尽管我们不支持许多第 1 阶段提案，但最近对管道运算符和 do 表达式进行了更新。因为我们已经支持这些提案，并且社区也对它们非常期待，所以我们将继续更新我们的实现。
```
这里指的应该是下面这个提案
https://github.com/tc39/proposal-do-expressions

2022-02-06 16:13 UTC, KimYangOfCat commented on docs/roadmap.md
> +还有其它提案（比如模式匹配）我们至今没有实现，因为它们的拥护者希望对语法和语义进行重大更改。然而，我们正在密切关注它们的发展，一旦它们稳定下来，我们就会在 Babel 中实现它们。
```suggestion
还有其它提案（比如模式匹配）我们至今没有实现，因为它们的拥护者希望对语法和语义进行重大更改。不过，我们正在密切关注它们的发展，一旦它们稳定下来，我们就会在 Babel 中实现它们。
```

2022-02-06 16:13 UTC, KimYangOfCat commented on docs/roadmap.md
> +- 在简单的项目中配置 Babel 将会更容易，你只需要在 `babel.config.json` 中启用 `compileJS: true` 选项（或者在将来它甚至可能是默认值 —— 它不能作为默认值是因为 `@babel/eslint-parser` 不编译源码）
```suggestion
- 在简单的项目中配置 Babel 将会更容易，你只需要在 `babel.config.json` 中启用 `compileJS: true` 选项（或者在将来它甚至可能是默认值 —— 目前它不能作为默认值是因为 `@babel/eslint-parser` 不编译源码）
```

2022-02-06 16:13 UTC, KimYangOfCat commented on docs/roadmap.md
> +- 当我们迁移至 ES 模块时，将很难在 `transformSync` 中同步解析和加载插件。这样可以防止它成为一个问题。
```suggestion
- 当我们迁移至 ES 模块时，将很难在 `transformSync` 中同步解析和加载插件。而这就可以解决前面的问题。
```

2022-02-06 16:13 UTC, KimYangOfCat commented on docs/roadmap.md
> +- 我们可以在 `@babel/preset-env` 中保留对 `core-js@3` 的支持，但在移动转译插件时，不能将其迁移到 `@babel/core`。
```suggestion
- 我们可以在 `@babel/preset-env` 中保留对 `core-js@3` 的支持，但在移动转译插件时，不将其迁移到 `@babel/core`。
```

2022-02-06 16:13 UTC, KimYangOfCat commented on docs/roadmap.md
> +- 我们需要实际实现必要的优化，确保它们仍然可以与其他插件很好地协同工作（因为它们会极大地增加可能的转译组合的数量）。
```suggestion
- 我们需要实际实现必要的优化，确保它们仍然可以与其他插件很好地协同工作（因为它们会极大地增加可能的转译组合数量）。
```

2022-02-06 16:13 UTC, KimYangOfCat commented on docs/roadmap.md
> +但是，我们只包含了在 `loose` 模式下编译时 _已经_ 做出的假设选项。我们现在可以调查我们的用户可能需要哪些新的假设。
```suggestion
但是，我们只包含了在 `loose` 模式下编译时 _已经_ 做出的假设选项。我们现在可以审查我们的用户可能需要哪些新的假设。
```

2022-02-06 16:13 UTC, KimYangOfCat commented on docs/roadmap.md
> +### 大修 Babel REPL
```suggestion
### 检修 Babel REPL
```

2022-02-06 16:13 UTC, KimYangOfCat commented on docs/roadmap.md
> +- REPL 不支持 `assumptions` 配置。尽管我们目前在 https://babel.dev/assumptions 上有一个专门基于每个假设的迷你 REPL，但我们不能说明这些 `assumptions` 是如何协同工作的
```suggestion
- REPL 不支持 `assumptions` 配置。尽管我们目前在 https://babel.dev/assumptions 上有一个专门基于每个假设的迷你 REPL，但我们不能展示这些 `assumptions` 是如何协同工作的
```

2022-02-09 11:37 UTC, htmlin commented on docs/roadmap.md
> +这远非我们将为 Babel 带来的所有新功能或重要更改的完整列表，但是，如果你对项目发展的大方向感兴趣，那么这是一个很好的总结。实际上，我们可能不能完成所有列出的要点，或者可能会将其中一些推迟到明年。其中一些有明确的起点和终点，而另一些则需要更多的研究或 [RFCs](https://github.com/babel/rfcs)。
```suggestion
这远不是我们将为 Babel 带来的所有新功能或重要更改的完整列表，但是，如果你对项目发展的大方向感兴趣，那么这是一个很好的总结。实际上，我们可能不能完成所有列出的要点，或者可能会将其中一些推迟到明年。其中一些有明确的起点和终点，而另一些则需要更多的研究或 [RFCs](https://github.com/babel/rfcs)。
```

2022-02-09 12:08 UTC, htmlin commented
> 感谢你的翻译，非常棒！麻烦再对其中一些校对意见进行修改吧，若有不同意见，欢迎讨论~

done

2022-02-09 14:08 UTC, KimYangOfCat approved these changes

2022-02-09 14:08 UTC, merged